---
- name: install pip
  apt: name=python-pip
  become: true

- name: install related dependencies
  apt: name={{ item }}
  become: true
  with_items:
    - build-essential
    - python-dev
    - pkg-config
    - libpng-dev
    - libjpeg8-dev
    - libfreetype6-dev

- name: install jupyter
  pip: name=jupyter
  become: true

- name: install py4j for pyspark
  pip: name=py4j
  become: true

- name: create notebook folder
  file:
    path: /usr/local/share/jupyter/notebook
    state: directory
  become: true

- name: create pyspark kernel folder
  file:
    path: /usr/local/share/jupyter/kernels/pyspark
    state: directory
  become: true

- name: create pyspark kernel config file
  template:
    src: pyspark_kernel.json.j2
    dest: /usr/local/share/jupyter/kernels/pyspark/kernel.json

- name: set spark defaults
  template:
    src: jupyter_spark_config.j2
    dest: {{ jupyter_spark_home }}/conf/spark-defaults.conf

- name: set upstart service
  template:
    src: upstart.conf.j2
    dest: /etc/init/jupyter.conf
  become: true

- name: start jupyter service
  service: name=jupyter state=started
  become: true

- name: install external python dependencies
  pip: name={{ item }}
  become: true
  with_items:
    - matplotlib
    - numpy
